# EmpiresOfAlan Configuration
# Version 2.0.0

# General Settings
general:
  # Default language (only en_US for now)
  language: en_US
  # Economy settings
  economy:
    # Starting balance for new towns
    town-starting-balance: 0.0
    # Starting balance for new nations
    nation-starting-balance: 0.0

# Town Settings
towns:
  # Minimum characters for town name
  min-name-length: 3
  # Maximum characters for town name
  max-name-length: 16
  # Allowed characters in town name (regex)
  name-regex: "[a-zA-Z0-9_]+"
  # Auto-claim surrounding chunks on creation
  auto-claim-surrounding: true

# Nation Settings
nations:
  # Minimum characters for nation name
  min-name-length: 3
  # Maximum characters for nation name
  max-name-length: 20
  # Allowed characters in nation name (regex)
  name-regex: "[a-zA-Z0-9_]+"
  # Maximum towns per nation (0 for unlimited)
  max-towns: 0

# Chunk Claim Settings
chunk-claim:
  # Base chunk limit
  base-limit: 5
  # Free chunks before cost applies
  free-chunks: 10
  # Cost per chunk after free limit
  claim-cost: 50.0
  # Payment priority: town-first or player-first
  pay-priority: town-first
  # Bonus chunks per player
  per-player-bonus: 10
  # Bonus chunks for 5+ players
  five-player-bonus: 15

# Claim Visualization Settings
claims:
  visualization:
    # Whether to show particles at claim borders
    enabled: true
    # Particle type for border visualization
    particle-type: FLAME
    # How long visualization lasts (in seconds)
    duration: 10
  # Protection settings
  protection:
    # Default flags for new claims
    defaults:
      pvp: false
      explosions: false
      mob-spawning: true
      fire-spread: false
      build: false
      interact: false
      public-spawn: false

# Tax Settings
taxes:
  # Whether taxes are enabled
  enabled: true
  # Town tax collection interval (in milliseconds)
  town-interval: 86400000 # 24 hours
  # Nation tax collection interval (in milliseconds)
  nation-interval: 86400000 # 24 hours

# Teleport Settings
teleports:
  # Cooldown between teleports (in seconds)
  cooldown: 30
  # Warmup time before teleport (in seconds)
  warmup: 3
  # Whether to cancel teleport on movement
  cancel-on-move: true

# Persistence Settings
persistence:
  # Save interval in minutes
  save-interval-minutes: 5

# Chat Settings
chat:
  # Show town name in chat
  show-town: true
  # Show nation name in chat
  show-nation: true
  # Format for town/nation info: {town} and {nation} are placeholders
  format: "[{town}|{nation}]"
  # Global chat format: {0}=town, {1}=nation, {2}=player, {3}=message
  global-format: "&7[&e{0}&7|&9{1}&7] &f{2}&f: &7{3}"
  # Town chat format: {0}=town, {1}=player, {2}=message
  town-format: "&b[{0}] &f{1}&f: &7{2}"
  # Nation chat format: {0}=nation, {1}=player, {2}=message
  nation-format: "&9[{0}] &f{1}&f: &7{2}"

# List Settings
list:
  # Number of towns to show per page
  towns-per-page: 10
  # Number of nations to show per page
  nations-per-page: 10